name: example
description: A sample Dart application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  envystic: ^0.4.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  envystic_generator: ^0.4.0+1
  lints: ^2.0.0
  test: ^1.21.0
