name: envystic

packages:
  - "**"

command:
  bootstrap:
    usePubspecOverrides: true

# To run a script use command: dart run melos run <script>
scripts:
  test:
    run: dart run melos exec --no-private -c 1 "dart test --coverage=coverage"
    env:
      SYSTEM_VAR: system_var
  lcov:
    run: dart run melos exec  --no-private -c 1 "dart pub global run coverage:test_with_coverage"
    env:
      SYSTEM_VAR: system_var
  coverage:
    run: dart run melos exec  --no-private -c 1 "dart pub global run code_coverage -u -o"
    env:
      SYSTEM_VAR: system_var
  validate: >
    dart run melos exec -c 1 "dart analyze && dart format . --set-exit-if-changed"
  format: >
    dart run melos exec -c 1 "dart format ."
  doc: >
    dart run melos exec -c 1 --ignore="example/**" "dart doc ."
  env:
    run: dart run scripts/propagate_readme.dart 
    env:
      SYSTEM_VAR: 'system_var'