builders:
  envystic:
    import: "package:envystic_generator/builder.dart"
    builder_factories: ["envysticBuilder"]
    build_extensions: { ".dart": [".envystic.g.part"] }
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]