targets:
  $default:
    builders:
      envystic_generator|envystic:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  envystic:
    import: "package:envystic_generator/builder.dart"
    builder_factories: ["envysticBuilder"]
    build_extensions: { ".dart": [".envystic.g.part"] }
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]