name: envystic_generator
description: Code generator for Envystic package - Simplifies Dart/Flutter env var management. Secure & organized.
version: 0.2.0+1
repository: https://github.com/itisnajim/envystic
issue_tracker: https://github.com/itisnajim/envystic/issues

environment:
  sdk: ^3.0.5

dependencies:
  envystic: ^0.2.0+1
  build: ^2.4.1
  logging: ^1.2.0
  analyzer: ^6.0.0
  source_gen: ^1.4.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
  source_gen_test: ^1.0.6
