name: envystic
description: "Env Variable Maestro! Seamlessly master config from remote sources, pre-stored via build_runner, or straight from the running system. Enchanting code, mystical security! ✨🌟"

version: 0.4.0
repository: https://github.com/itisnajim/envystic
issue_tracker: https://github.com/itisnajim/envystic/issues

topics:
  - dotenv
  - build-runner
  - codegen
  - encryption

environment:
  sdk: ^3.0.5

dependencies: 
  meta: ^1.9.1
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
