name: envystic
description: Simplify and Secure Your Environment Variables (dotenv file or system) in Dart/Flutter.
version: 0.2.0+2
repository: https://github.com/itisnajim/envystic
issue_tracker: https://github.com/itisnajim/envystic/issues

environment:
  sdk: ^3.0.5

dependencies: 
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
